CXX=clang++
CXXFLAGS= -std=c++17 -O3 -Wall -Wextra

.PHONY: clean 7_*

all:
	@echo "Please enter the number of excercise e.g. make 7_1"

7_1: 7_1.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./7_1.out
7_2: 7_2.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./7_2.out
7_3: 7_3.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./7_3.out
7_4: 7_4.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./7_4.out
7_5: 7_5.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./7_5.out
7_6: 7_6.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./7_6.out
7_7: 7_7.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./7_7.out
7_8: 7_8.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./7_8.out
7_9: 7_9.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./7_9.out
7_10: 7_10.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./7_10.out

clean:
	${RM} *.out

