CXX=clang++
CXXFLAGS= -std=c++17 -O3 -Wall -Wextra

.PHONY: clean 4_*

all:
	@echo "Please enter the number of excercise e.g. make 4_1"

4_1: 4_1.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./4_1.out
4_2: 4_2.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./4_2.out
4_3: 4_3.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./4_4.out
4_4: 4_4.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./4_4.out
4_5: 4_5.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./4_5.out
4_6: 4_6.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./4_6.out
4_7: 4_7.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./4_7.out

clean:
	${RM} *.out

