CXX = g++
CFLAGS = -O3 -Wall -Wextra
.PHONY: 1 2 3 4 5 6 7 clean

all:
	@echo "please use **make x**(x=1 ... 7) to specify which ans"
1: 2_1.cpp
	@$(CXX) $(CFALGS) -o 2_1 $<
	@./2_1

clean:
	@$(RM) *.o 2_1



