CXX = clang++
CFLAGS = std=c++17 -O3 -Wall -Wextra
.PHONY: 2_1 2_2 2_3 2_4 2_5 2_6 2_7 clean

all:
	@echo "please use **make 2_id** (id = 1...7) to specify which ans"
2_1: 2_1.cpp
	@$(CXX) $(CFALGS) -o $@.out $<
	@./$@.out
2_2: 2_2.cpp
	@$(CXX) $(CFALGS) -o $@.out $<
	@./$@.out
2_3: 2_3.cpp
	@$(CXX) $(CFALGS) -o $@.out $<
	@./$@.out
2_4: 2_4.cpp
	@$(CXX) $(CFALGS) -o $@.out $<
	@./$@.out
2_5: 2_5.cpp
	@$(CXX) $(CFALGS) -o $@.out $<
	@./$@.out
2_6: 2_6.cpp
	@$(CXX) $(CFALGS) -o $@.out $<
	@./$@.out
2_7: 2_7.cpp
	@$(CXX) $(CFALGS) -o $@.out $<
	@./$@.out

clean:
	@$(RM) *.out


