CXX=clang++
CXXFLAGS= -std=c++17 -O3 -Wall -Wextra

.PHONY: clean 6_*

all:
	@echo "Please enter the number of excercise e.g. make 6_1"

6_1: 6_1.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./6_1.out
6_2: 6_2.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./6_2.out
6_3: 6_3.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./6_3.out
6_4: 6_4.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./6_4.out
6_5: 6_5.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./6_5.out
6_6: 6_6.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./6_6.out
6_7: 6_7.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./6_7.out
6_8: 6_8.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./6_8.out
6_9: 6_9.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./6_9.out
6_10: 6_10.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./6_10.out

clean:
	${RM} *.out

