CXX=clang++
CXXFLAGS= -std=c++17 -O3 -Wall -Wextra

.PHONY: clean 9_*

all:
	@echo "Please enter the number of excercise e.g. make 9_1"

9_2: 9_2.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./9_2.out
9_3: 9_3.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./9_3.out
9_4: 9_4.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./9_4.out
9_5: 9_5.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./9_5.out
9_6: 9_6.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./9_6.out
9_7: 9_7.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./9_7.out
9_8: 9_8.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./9_8.out
9_9: 9_9.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./9_9.out
9_10: 9_10.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./9_10.out

clean:
	${RM} *.out

