CXX=clang++
CXXFLAGS= -std=c++17 -O3 -Wall -Wextra

.PHONY: clean 8_*

all:
	@echo "Please enter the number of excercise e.g. make 8_1"

8_1: 8_1.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./8_1.out
8_2: 8_2.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./8_2.out
8_3: 8_3.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./8_3.out
8_4: 8_4.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./8_4.out
8_5: 8_5.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./8_5.out
8_6: 8_6.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./8_6.out
8_7: 8_7.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./8_7.out
8_8: 8_8.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./8_8.out
8_9: 8_9.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./8_9.out
8_10: 8_10.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./8_10.out

clean:
	${RM} *.out

