CXX=clang++
CXXFLAGS= -std=c++17 -O3 -Wall -Wextra

.PHONY: clean 5_*

all:
	@echo "Please enter the number of excercise e.g. make 5_1"

5_1: 5_1.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./5_1.out
5_2: 5_2.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./5_2.out
5_3: 5_3.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./5_3.out
5_4: 5_4.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./5_4.out
5_5: 5_5.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./5_5.out
5_6: 5_6.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./5_6.out
5_7: 5_7.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./5_7.out
5_8: 5_8.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./5_8.out
5_9: 5_9.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./5_9.out
5_10: 5_10.cpp
	@${CXX} ${CXXFLAGS} -o $@.out $^
	@./5_10.out

clean:
	${RM} *.out

